plugins {
	id 'java-library'
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'idea'
}

version = project.mod_version + "+fabric+mc" + project.minecraft_version
group = project.mod_group

base {
	archivesName = project.mod_id
}

repositories {
	maven {
		name = 'Fabric'
		url = 'https://maven.fabricmc.net/'
	}
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	// Fabric loader.
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	// Fabric API.
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

idea {
	module {
		// Download sources/javadoc jars for dependencies.
		downloadSources = true
		downloadJavadoc = true
	}
}

processResources {
	filesMatching("fabric.mod.json") {
		expand "mod_id": project.mod_id,
			"mod_version": project.mod_version,
			"version": project.version,
			"minecraft_version": "~${project.minecraft_version}",
			"loader_version": ">=${project.loader_version}",
			"fabric_version": ">=${project.fabric_version}"
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = 'UTF-8'
	it.options.release = 25
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
	toolchain.languageVersion = JavaLanguageVersion.of(25)
}

jar {
	from("LICENSE")
}
