# Default gradle parameters.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Fabric Properties.
# https://fabricmc.net/develop/
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties.
mod_group=eu.pintergabor.dirtcheap
mod_id=dirtcheap
mod_version=1.1.8

# Dependencies.
# https://fabricmc.net/develop/
fabric_version=0.154.2+26.1.2
